import type { MeshEvent, UtmParams } from "@meshlytics/core";

export interface PlanRoute {
  path: string;
  params: {
    routeParams: boolean;
    queryParams: boolean;
    utmParams: boolean;
    referrer: boolean;
  };
}

/**
 * Lightweight mirror of `InstrumentationPlan` from `@meshlytics/schema`,
 * kept dependency-free so the SDK never pulls zod into a client bundle.
 * This is the shape `meshlytics instrument` writes into generated code.
 */
export interface MeshlyticsPlan {
  version: 1;
  generatedAt: string;
  application: {
    framework: string;
    router: string;
  };
  routes: PlanRoute[];
}

export type EventTransport = (event: MeshEvent) => void | Promise<void>;

export interface MeshlyticsClientOptions {
  /** Instrumentation plan generated by `meshlytics instrument`. */
  plan?: MeshlyticsPlan;
  /** HTTP endpoint events are POSTed to. Ignored if `transport` is set. */
  endpoint?: string;
  /** Custom sink, e.g. to forward events to PostHog, Mixpanel, or Meshlytics Cloud. */
  transport?: EventTransport;
  /** Logs every emitted event to the console. Defaults to false. */
  debug?: boolean;
}

export interface PageOptions {
  route?: string;
  queryParams?: Record<string, string>;
  utm?: UtmParams;
  referrer?: string;
  properties?: Record<string, unknown>;
}

export interface MeshlyticsClient {
  track(name: string, properties?: Record<string, unknown>): void;
  page(options?: PageOptions): void;
  identify(id: string, traits?: Record<string, unknown>): void;
}
