import type { InstrumentationPlan } from "@meshlytics/schema";

const HEADER = `// This file is generated by \`meshlytics instrument\`.
// Re-run that command after changing meshlytics.config.json to regenerate it.
// Do not edit the tracked-route list by hand — edit the config instead.
`;

/**
 * Renders an instrumentation plan into a standalone TypeScript module
 * that initializes the Meshlytics SDK with every tracked route and
 * its parameter-capture settings.
 */
export function generateInstrumentationModule(plan: InstrumentationPlan): string {
  const routesLiteral = plan.tracked
    .map(
      (tracked) => `  {
    path: ${JSON.stringify(tracked.route.path)},
    params: {
      routeParams: ${tracked.params.routeParams},
      queryParams: ${tracked.params.queryParams},
      utmParams: ${tracked.params.utmParams},
      referrer: ${tracked.params.referrer},
    },
  }`,
    )
    .join(",\n");

  return `${HEADER}
import { createClient } from "meshlytics";

export const meshlytics = createClient({
  plan: {
    version: ${plan.version},
    generatedAt: ${JSON.stringify(plan.generatedAt)},
    application: {
      framework: ${JSON.stringify(plan.application.framework)},
      router: ${JSON.stringify(plan.application.router)},
    },
    routes: [
${routesLiteral}
    ],
  },
});
`;
}
