import { describe, expect, it } from "vitest";
import type { InstrumentationPlan } from "@meshlytics/schema";
import { generateInstrumentationModule } from "./generate.js";

const plan: InstrumentationPlan = {
  version: 1,
  generatedAt: "2026-09-06T12:00:00.000Z",
  application: {
    framework: "next",
    router: "app",
    typescript: true,
    rootDir: "/app",
    routes: [{ path: "/", file: "page.tsx", dynamicSegments: [] }],
  },
  tracked: [
    {
      route: { path: "/", file: "page.tsx", dynamicSegments: [] },
      params: { routeParams: true, queryParams: false, utmParams: true, referrer: true },
    },
    {
      route: { path: "/checkout", file: "checkout/page.tsx", dynamicSegments: [] },
      params: { routeParams: false, queryParams: true, utmParams: false, referrer: false },
    },
  ],
};

describe("generateInstrumentationModule", () => {
  const output = generateInstrumentationModule(plan);

  it("imports createClient from the meshlytics package", () => {
    expect(output).toContain('import { createClient } from "meshlytics";');
  });

  it("exports a meshlytics client built from the plan", () => {
    expect(output).toContain("export const meshlytics = createClient({");
  });

  it("includes every tracked route's path", () => {
    expect(output).toContain('path: "/",');
    expect(output).toContain('path: "/checkout",');
  });

  it("renders each route's own parameter config, not a shared default", () => {
    expect(output).toMatch(/path: "\/",\s*params: \{\s*routeParams: true,\s*queryParams: false,\s*utmParams: true,\s*referrer: true,/);
    expect(output).toMatch(/path: "\/checkout",\s*params: \{\s*routeParams: false,\s*queryParams: true,\s*utmParams: false,\s*referrer: false,/);
  });

  it("carries the plan version, generatedAt, and application metadata", () => {
    expect(output).toContain("version: 1,");
    expect(output).toContain('generatedAt: "2026-09-06T12:00:00.000Z",');
    expect(output).toContain('framework: "next",');
    expect(output).toContain('router: "app",');
  });

  it("leads with a generated-file warning comment", () => {
    expect(output.startsWith("// This file is generated by `meshlytics instrument`.")).toBe(true);
  });

  it("produces an empty routes array when nothing is tracked", () => {
    const empty = generateInstrumentationModule({ ...plan, tracked: [] });
    expect(empty).toContain("routes: [\n\n    ],");
  });
});
